version: 0.10.1-{build}

image: Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

before_build:
  - dotnet restore --verbosity m

build_script:
  - dotnet build SODA.sln

test_script:
  - dotnet test

notifications:
  - provider: GitHubPullRequest